repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # You can specify a specific version or the latest tag.
    hooks:
      - id: black
        args: ["--check"]

  
  - repo: https://github.com/pycqa/flake8
    rev: ''  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
  
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: ./venv/bin/pytest src
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
